spellername = "Northern Kurdish"
spellerversion = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Northern Kurdish spellchecker"
kmr = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Northern Kurdish, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
kmr = "TRANSLATE: A spellchecker for Northern Kurdish, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.kmr"

[windows]
system_product_code = "{54ED9493-FEF0-4657-9EC5-0718C50D0E74}_is1"
legacy_product_codes = [
    { value = "6C796295-D4BB-498F-9888-312D8956AC3C", kind = "nsis" },
    { value = "EA471F56-0E4E-4530-B6E7-AA7418973561", kind = "nsis" }
]
