template = "https://github.com/giellalt/template-lang-und"
rev_id = 211
template_sha = "10e685dd04eec221fd395793c4cce31a2b65e23d"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
