template = "https://github.com/giellalt/template-lang-und"
rev_id = 77
template_sha = "0e397b985c7c0a4703eee3c093c0d443b12ed1a2"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
