template = "https://github.com/giellalt/template-lang-und"
rev_id = 109
template_sha = "d40a7692cf2e8c611db26b8a45234f6db8ec5744"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
