template = "https://github.com/giellalt/template-lang-und"
rev_id = 226
template_sha = "821b934c201a86aa026fe8f829b68e551781055d"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
