template = "https://github.com/giellalt/template-lang-und"
rev_id = 91
template_sha = "db86852b32e4d9cf1a824e26d07e7b3cd00b8246"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
