template = "https://github.com/giellalt/template-lang-und"
rev_id = 173
template_sha = "7f7aaa49ffc6ff6884deab8fb0fe6cae98efc3b8"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
