template = "https://github.com/giellalt/template-lang-und"
rev_id = 192
template_sha = "02ff4d9dc4e819c21ed53241bd49228e7a3c5dfd"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
