template = "https://github.com/giellalt/template-lang-und"
rev_id = 204
template_sha = "e2882c9d970daa8699f93d44a4d2440eae448af4"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
