template = "https://github.com/giellalt/template-lang-und"
rev_id = 250
template_sha = "fc3ee4b759f7e4d74e61feb6577fcefe25384f4a"

[replacements]
__GLOTTOLOG_ID__ = "nort2641"
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
