template = "https://github.com/giellalt/template-lang-und"
rev_id = 217
template_sha = "e053fa013b57654fcea7319fd6dba18be2c1aaea"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
