template = "https://github.com/giellalt/template-lang-und"
rev_id = 103
template_sha = "9004feb674fd3fd06f5e92fdf7f94148f238dfad"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
