template = "https://github.com/giellalt/template-lang-und"
rev_id = 162
template_sha = "72e0484a46ee787ac0c21dde10da1714de8e9a70"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
