template = "https://github.com/giellalt/template-lang-und"
rev_id = 204
template_sha = "8eab0289bf8affc67c3fd50e60d031c9ba59c3e5"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
