template = "https://github.com/giellalt/template-lang-und"
rev_id = 248
template_sha = "74f75a180d741e4c2345538f6a6f98a34de2f199"

[replacements]
__GLOTTOLOG_ID__ = "nort2641"
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
