template = "https://github.com/giellalt/template-lang-und"
rev_id = 90
template_sha = "8f6d43a830bf1731376b169084c667c47e70f1f8"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
