template = "https://github.com/giellalt/template-lang-und"
rev_id = 230
template_sha = "f93135dcd0289587f23ccda4a615f9d6f4abe835"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
