template = "https://github.com/giellalt/template-lang-und"
rev_id = 140
template_sha = "2476cce826a5f41f0a1868d4166d67d269a0cc4d"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
