template = "https://github.com/giellalt/template-lang-und"
rev_id = 253
template_sha = "7b8a6c39a9307995ad9926ecd5b777ca888b3659"

[replacements]
__GLOTTOLOG_ID__ = "nort2641"
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
