template = "https://github.com/giellalt/template-lang-und"
rev_id = 72
template_sha = "c86354124e8c85876e17c4bb07ea17433bd16f19"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
