template = "https://github.com/giellalt/template-lang-und"
rev_id = 158
template_sha = "32119e63e005800ea7d68ea841059c47f02cb6db"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
