template = "https://github.com/giellalt/template-lang-und"
rev_id = 185
template_sha = "ab0921ee1e75a04739e82be4750888e8da80f1db"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
