template = "https://github.com/giellalt/template-lang-und"
rev_id = 251
template_sha = "fb831d8496f6207a123362fece622ed5e22ef617"

[replacements]
__GLOTTOLOG_ID__ = "nort2641"
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
