template = "https://github.com/giellalt/template-lang-und"
rev_id = 235
template_sha = "4b9bff4b28cc1e21832b597fb7b8c3f34524976d"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
