template = "https://github.com/giellalt/template-lang-und"
rev_id = 239
template_sha = "0ad4d24907fe48e56692e2c8d2ac749fd207326c"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
