template = "https://github.com/giellalt/template-lang-und"
rev_id = 99
template_sha = "005ab3eef53b57ae6e87aa8645d004418a358350"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
