template = "https://github.com/giellalt/template-lang-und"
rev_id = 197
template_sha = "bdbeb58949a48fb6da495bd72088ee0ffd09c956"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
