template = "https://github.com/giellalt/template-lang-und"
rev_id = 153
template_sha = "ca1a4ee19d234d19c768d1d0646f1a87a67bc6d7"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
