template = "https://github.com/giellalt/template-lang-und"
rev_id = 201
template_sha = "76e63277b94d32830ca81b7200101b801abf1913"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
