template = "https://github.com/giellalt/template-lang-und"
rev_id = 126
template_sha = "ad3624086df0730923a482ae4a48948c2ea37419"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
