template = "https://github.com/giellalt/template-lang-und"
rev_id = 80
template_sha = "e72c0a0abd24b9bfbe84351026d3918849536e1f"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
