template = "https://github.com/giellalt/template-lang-und"
rev_id = 78
template_sha = "7794d418829530e1c36b5fb617a4ed8fdd36a709"

[replacements]
__REPO__ = "lang-kmr"
__UND2C__ = "kmr"
__UNDEFINED__ = "Northern Kurdish"
__UND__ = "kmr"
